name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs on the 0, 6, 12 and 18th hour
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    name: "Update this repo's README WAKA Graph"
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@c59d497f95bb9e5c10bb90d5a6597fb5cb223508
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROJECTS: false
          SHOW_OS: false
          SHOW_TIMEZONE: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
