name: Update profile

on:
  workflow_dispatch:
  schedule:
    # Runs on the 0, 6, 12 and 18th hour
    - cron: "0 */2 * * *"

jobs:
  wakatime:
    name: "Update this repo's README WAKA Graph"
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@c59d497f95bb9e5c10bb90d5a6597fb5cb223508
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROJECTS: false
          SHOW_OS: false
          SHOW_TIMEZONE: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          COMMIT_MESSAGE: "chore: update waka graph with new metrics"
          
  sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          file: 'README.md'
          template: '* [{{{ name }}}]({{{ url }}}) - {{{ login }}}'
